# this is default config file 

spring:
  application:
    name: ConfigServer
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

